---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "neo-fixit.fullname" . }}-srv
  labels:
    {{- include "neo-fixit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 8080
    {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
    name: http 
  selector:
    {{- include "neo-fixit.selectorLabels" . | nindent 4 }}
